apiVersion: apps/v1
kind: Deployment
metadata:
  name: commande-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commande-service
  template:
    metadata:
      labels:
        app: commande-service
    spec:
      containers:
        - name: commande-service
          image: commande-service:1.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data
              name: commande-storage
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: CONFIG_SERVER_URL
              value: http://config-service:8888
            - name: EUREKA_SERVER_URL
              value: http://discovery-service:8761/eureka
      volumes:
        - name: commande-storage
          persistentVolumeClaim:
            claimName: commande-pvc